# Generated by Django 4.2.4 on 2023-08-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0006_remove_resources_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
