# Generated by Django 4.2.4 on 2023-09-07 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0008_resourcestag_resource_tag_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resources",
            options={"verbose_name_plural": "Resources"},
        ),
    ]
